// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ShopStatus int32

const (
	ShopStatus_ShopStatusDefault ShopStatus = 0
	ShopStatus_ShopStatusOpen    ShopStatus = 1
	ShopStatus_ShopStatusClose   ShopStatus = 2
)

var ShopStatus_name = map[int32]string{
	0: "ShopStatusDefault",
	1: "ShopStatusOpen",
	2: "ShopStatusClose",
}
var ShopStatus_value = map[string]int32{
	"ShopStatusDefault": 0,
	"ShopStatusOpen":    1,
	"ShopStatusClose":   2,
}

func (x ShopStatus) String() string {
	return proto.EnumName(ShopStatus_name, int32(x))
}
func (ShopStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ShopInfo struct {
	ShopId             uint64     `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Name               string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	BusinessHoursStart int64      `protobuf:"varint,3,opt,name=businessHoursStart" json:"businessHoursStart,omitempty"`
	BusinessHoursEnd   int64      `protobuf:"varint,4,opt,name=businessHoursEnd" json:"businessHoursEnd,omitempty"`
	ShopStatus         ShopStatus `protobuf:"varint,5,opt,name=shopStatus,enum=merchant.pkg.rpc.protos.ShopStatus" json:"shopStatus,omitempty"`
	ShopType           int64      `protobuf:"varint,6,opt,name=shopType" json:"shopType,omitempty"`
	MerchantId         uint64     `protobuf:"varint,7,opt,name=merchantId" json:"merchantId,omitempty"`
	CreatedAt          string     `protobuf:"bytes,8,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt          string     `protobuf:"bytes,9,opt,name=updatedAt" json:"updatedAt,omitempty"`
	VerifierMobiles    []string   `protobuf:"bytes,10,rep,name=verifierMobiles" json:"verifierMobiles,omitempty"`
	FuYouMerchantId    string     `protobuf:"bytes,11,opt,name=fuYouMerchantId" json:"fuYouMerchantId,omitempty"`
	IsRebate           bool       `protobuf:"varint,12,opt,name=isRebate" json:"isRebate,omitempty"`
}

func (m *ShopInfo) Reset()                    { *m = ShopInfo{} }
func (m *ShopInfo) String() string            { return proto.CompactTextString(m) }
func (*ShopInfo) ProtoMessage()               {}
func (*ShopInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ShopInfo) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShopInfo) GetBusinessHoursStart() int64 {
	if m != nil {
		return m.BusinessHoursStart
	}
	return 0
}

func (m *ShopInfo) GetBusinessHoursEnd() int64 {
	if m != nil {
		return m.BusinessHoursEnd
	}
	return 0
}

func (m *ShopInfo) GetShopStatus() ShopStatus {
	if m != nil {
		return m.ShopStatus
	}
	return ShopStatus_ShopStatusDefault
}

func (m *ShopInfo) GetShopType() int64 {
	if m != nil {
		return m.ShopType
	}
	return 0
}

func (m *ShopInfo) GetMerchantId() uint64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *ShopInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ShopInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ShopInfo) GetVerifierMobiles() []string {
	if m != nil {
		return m.VerifierMobiles
	}
	return nil
}

func (m *ShopInfo) GetFuYouMerchantId() string {
	if m != nil {
		return m.FuYouMerchantId
	}
	return ""
}

func (m *ShopInfo) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

type CreateShopRequest struct {
	MerchantId         uint64     `protobuf:"varint,1,opt,name=merchantId" json:"merchantId,omitempty"`
	Name               string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	BusinessHoursStart int64      `protobuf:"varint,3,opt,name=businessHoursStart" json:"businessHoursStart,omitempty"`
	BusinessHoursEnd   int64      `protobuf:"varint,4,opt,name=businessHoursEnd" json:"businessHoursEnd,omitempty"`
	ShopStatus         ShopStatus `protobuf:"varint,5,opt,name=shopStatus,enum=merchant.pkg.rpc.protos.ShopStatus" json:"shopStatus,omitempty"`
	ShopType           int64      `protobuf:"varint,6,opt,name=shopType" json:"shopType,omitempty"`
	VerifierMobiles    []string   `protobuf:"bytes,7,rep,name=verifierMobiles" json:"verifierMobiles,omitempty"`
	FuYouMerchantId    string     `protobuf:"bytes,8,opt,name=fuYouMerchantId" json:"fuYouMerchantId,omitempty"`
	IsRebate           bool       `protobuf:"varint,9,opt,name=isRebate" json:"isRebate,omitempty"`
}

func (m *CreateShopRequest) Reset()                    { *m = CreateShopRequest{} }
func (m *CreateShopRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateShopRequest) ProtoMessage()               {}
func (*CreateShopRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateShopRequest) GetMerchantId() uint64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *CreateShopRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateShopRequest) GetBusinessHoursStart() int64 {
	if m != nil {
		return m.BusinessHoursStart
	}
	return 0
}

func (m *CreateShopRequest) GetBusinessHoursEnd() int64 {
	if m != nil {
		return m.BusinessHoursEnd
	}
	return 0
}

func (m *CreateShopRequest) GetShopStatus() ShopStatus {
	if m != nil {
		return m.ShopStatus
	}
	return ShopStatus_ShopStatusDefault
}

func (m *CreateShopRequest) GetShopType() int64 {
	if m != nil {
		return m.ShopType
	}
	return 0
}

func (m *CreateShopRequest) GetVerifierMobiles() []string {
	if m != nil {
		return m.VerifierMobiles
	}
	return nil
}

func (m *CreateShopRequest) GetFuYouMerchantId() string {
	if m != nil {
		return m.FuYouMerchantId
	}
	return ""
}

func (m *CreateShopRequest) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

type CreateShopReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *CreateShopReply) Reset()                    { *m = CreateShopReply{} }
func (m *CreateShopReply) String() string            { return proto.CompactTextString(m) }
func (*CreateShopReply) ProtoMessage()               {}
func (*CreateShopReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CreateShopReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreateShopReply) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetShopListRequest struct {
	MerchantId uint64     `protobuf:"varint,1,opt,name=merchantId" json:"merchantId,omitempty"`
	ShopStatus ShopStatus `protobuf:"varint,2,opt,name=shopStatus,enum=merchant.pkg.rpc.protos.ShopStatus" json:"shopStatus,omitempty"`
	ShopId     uint64     `protobuf:"varint,3,opt,name=shopId" json:"shopId,omitempty"`
	Page       uint64     `protobuf:"varint,4,opt,name=page" json:"page,omitempty"`
	PageSize   uint64     `protobuf:"varint,5,opt,name=pageSize" json:"pageSize,omitempty"`
	ShopName   string     `protobuf:"bytes,6,opt,name=shopName" json:"shopName,omitempty"`
}

func (m *GetShopListRequest) Reset()                    { *m = GetShopListRequest{} }
func (m *GetShopListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetShopListRequest) ProtoMessage()               {}
func (*GetShopListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetShopListRequest) GetMerchantId() uint64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *GetShopListRequest) GetShopStatus() ShopStatus {
	if m != nil {
		return m.ShopStatus
	}
	return ShopStatus_ShopStatusDefault
}

func (m *GetShopListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetShopListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetShopListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetShopListRequest) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

type GetShopListReply struct {
	Err      *Error      `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	ShopList []*ShopInfo `protobuf:"bytes,2,rep,name=ShopList" json:"ShopList,omitempty"`
	Count    uint64      `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetShopListReply) Reset()                    { *m = GetShopListReply{} }
func (m *GetShopListReply) String() string            { return proto.CompactTextString(m) }
func (*GetShopListReply) ProtoMessage()               {}
func (*GetShopListReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GetShopListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetShopListReply) GetShopList() []*ShopInfo {
	if m != nil {
		return m.ShopList
	}
	return nil
}

func (m *GetShopListReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetShopInfoRequest struct {
	ShopId uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetShopInfoRequest) Reset()                    { *m = GetShopInfoRequest{} }
func (m *GetShopInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetShopInfoRequest) ProtoMessage()               {}
func (*GetShopInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GetShopInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetShopInfoReply struct {
	ShopInfo *ShopInfo `protobuf:"bytes,1,opt,name=ShopInfo" json:"ShopInfo,omitempty"`
	Err      *Error    `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *GetShopInfoReply) Reset()                    { *m = GetShopInfoReply{} }
func (m *GetShopInfoReply) String() string            { return proto.CompactTextString(m) }
func (*GetShopInfoReply) ProtoMessage()               {}
func (*GetShopInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetShopInfoReply) GetShopInfo() *ShopInfo {
	if m != nil {
		return m.ShopInfo
	}
	return nil
}

func (m *GetShopInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type ModifyShopInfoRequest struct {
	Name               string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BusinessHoursStart int64      `protobuf:"varint,2,opt,name=businessHoursStart" json:"businessHoursStart,omitempty"`
	BusinessHoursEnd   int64      `protobuf:"varint,3,opt,name=businessHoursEnd" json:"businessHoursEnd,omitempty"`
	ShopStatus         ShopStatus `protobuf:"varint,4,opt,name=shopStatus,enum=merchant.pkg.rpc.protos.ShopStatus" json:"shopStatus,omitempty"`
	ShopType           int64      `protobuf:"varint,5,opt,name=shopType" json:"shopType,omitempty"`
	ShopId             uint64     `protobuf:"varint,6,opt,name=shopId" json:"shopId,omitempty"`
	MerchantId         uint64     `protobuf:"varint,7,opt,name=merchantId" json:"merchantId,omitempty"`
	VerifierMobiles    []string   `protobuf:"bytes,8,rep,name=verifierMobiles" json:"verifierMobiles,omitempty"`
	FuYouMerchantId    string     `protobuf:"bytes,9,opt,name=fuYouMerchantId" json:"fuYouMerchantId,omitempty"`
	IsRebate           bool       `protobuf:"varint,10,opt,name=isRebate" json:"isRebate,omitempty"`
}

func (m *ModifyShopInfoRequest) Reset()                    { *m = ModifyShopInfoRequest{} }
func (m *ModifyShopInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyShopInfoRequest) ProtoMessage()               {}
func (*ModifyShopInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *ModifyShopInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyShopInfoRequest) GetBusinessHoursStart() int64 {
	if m != nil {
		return m.BusinessHoursStart
	}
	return 0
}

func (m *ModifyShopInfoRequest) GetBusinessHoursEnd() int64 {
	if m != nil {
		return m.BusinessHoursEnd
	}
	return 0
}

func (m *ModifyShopInfoRequest) GetShopStatus() ShopStatus {
	if m != nil {
		return m.ShopStatus
	}
	return ShopStatus_ShopStatusDefault
}

func (m *ModifyShopInfoRequest) GetShopType() int64 {
	if m != nil {
		return m.ShopType
	}
	return 0
}

func (m *ModifyShopInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ModifyShopInfoRequest) GetMerchantId() uint64 {
	if m != nil {
		return m.MerchantId
	}
	return 0
}

func (m *ModifyShopInfoRequest) GetVerifierMobiles() []string {
	if m != nil {
		return m.VerifierMobiles
	}
	return nil
}

func (m *ModifyShopInfoRequest) GetFuYouMerchantId() string {
	if m != nil {
		return m.FuYouMerchantId
	}
	return ""
}

func (m *ModifyShopInfoRequest) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

type ModifyShopReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *ModifyShopReply) Reset()                    { *m = ModifyShopReply{} }
func (m *ModifyShopReply) String() string            { return proto.CompactTextString(m) }
func (*ModifyShopReply) ProtoMessage()               {}
func (*ModifyShopReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ModifyShopReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ModifyShopReply) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type CheckMobileAccessRequest struct {
	Mobile string `protobuf:"bytes,1,opt,name=mobile" json:"mobile,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *CheckMobileAccessRequest) Reset()                    { *m = CheckMobileAccessRequest{} }
func (m *CheckMobileAccessRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckMobileAccessRequest) ProtoMessage()               {}
func (*CheckMobileAccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *CheckMobileAccessRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CheckMobileAccessRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type CheckMobileAccessReply struct {
	Err        *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	IsVerifier bool   `protobuf:"varint,2,opt,name=isVerifier" json:"isVerifier,omitempty"`
}

func (m *CheckMobileAccessReply) Reset()                    { *m = CheckMobileAccessReply{} }
func (m *CheckMobileAccessReply) String() string            { return proto.CompactTextString(m) }
func (*CheckMobileAccessReply) ProtoMessage()               {}
func (*CheckMobileAccessReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *CheckMobileAccessReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CheckMobileAccessReply) GetIsVerifier() bool {
	if m != nil {
		return m.IsVerifier
	}
	return false
}

func init() {
	proto.RegisterType((*ShopInfo)(nil), "merchant.pkg.rpc.protos.ShopInfo")
	proto.RegisterType((*CreateShopRequest)(nil), "merchant.pkg.rpc.protos.CreateShopRequest")
	proto.RegisterType((*CreateShopReply)(nil), "merchant.pkg.rpc.protos.CreateShopReply")
	proto.RegisterType((*GetShopListRequest)(nil), "merchant.pkg.rpc.protos.GetShopListRequest")
	proto.RegisterType((*GetShopListReply)(nil), "merchant.pkg.rpc.protos.GetShopListReply")
	proto.RegisterType((*GetShopInfoRequest)(nil), "merchant.pkg.rpc.protos.GetShopInfoRequest")
	proto.RegisterType((*GetShopInfoReply)(nil), "merchant.pkg.rpc.protos.GetShopInfoReply")
	proto.RegisterType((*ModifyShopInfoRequest)(nil), "merchant.pkg.rpc.protos.ModifyShopInfoRequest")
	proto.RegisterType((*ModifyShopReply)(nil), "merchant.pkg.rpc.protos.ModifyShopReply")
	proto.RegisterType((*CheckMobileAccessRequest)(nil), "merchant.pkg.rpc.protos.CheckMobileAccessRequest")
	proto.RegisterType((*CheckMobileAccessReply)(nil), "merchant.pkg.rpc.protos.CheckMobileAccessReply")
	proto.RegisterEnum("merchant.pkg.rpc.protos.ShopStatus", ShopStatus_name, ShopStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShopController service

type ShopControllerClient interface {
	// 商家店铺创建
	CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopReply, error)
	// 商铺列表
	GetShopList(ctx context.Context, in *GetShopListRequest, opts ...grpc.CallOption) (*GetShopListReply, error)
	// 商铺详情
	GetShopInfo(ctx context.Context, in *GetShopInfoRequest, opts ...grpc.CallOption) (*GetShopInfoReply, error)
	// 修改商铺
	ModifyShopInfo(ctx context.Context, in *ModifyShopInfoRequest, opts ...grpc.CallOption) (*ModifyShopReply, error)
	// 校验该用户是否是该商铺的核销员
	CheckMobileAccess(ctx context.Context, in *CheckMobileAccessRequest, opts ...grpc.CallOption) (*CheckMobileAccessReply, error)
}

type shopControllerClient struct {
	cc *grpc.ClientConn
}

func NewShopControllerClient(cc *grpc.ClientConn) ShopControllerClient {
	return &shopControllerClient{cc}
}

func (c *shopControllerClient) CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopReply, error) {
	out := new(CreateShopReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.ShopController/CreateShop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopControllerClient) GetShopList(ctx context.Context, in *GetShopListRequest, opts ...grpc.CallOption) (*GetShopListReply, error) {
	out := new(GetShopListReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.ShopController/GetShopList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopControllerClient) GetShopInfo(ctx context.Context, in *GetShopInfoRequest, opts ...grpc.CallOption) (*GetShopInfoReply, error) {
	out := new(GetShopInfoReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.ShopController/GetShopInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopControllerClient) ModifyShopInfo(ctx context.Context, in *ModifyShopInfoRequest, opts ...grpc.CallOption) (*ModifyShopReply, error) {
	out := new(ModifyShopReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.ShopController/ModifyShopInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopControllerClient) CheckMobileAccess(ctx context.Context, in *CheckMobileAccessRequest, opts ...grpc.CallOption) (*CheckMobileAccessReply, error) {
	out := new(CheckMobileAccessReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.ShopController/CheckMobileAccess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShopController service

type ShopControllerServer interface {
	// 商家店铺创建
	CreateShop(context.Context, *CreateShopRequest) (*CreateShopReply, error)
	// 商铺列表
	GetShopList(context.Context, *GetShopListRequest) (*GetShopListReply, error)
	// 商铺详情
	GetShopInfo(context.Context, *GetShopInfoRequest) (*GetShopInfoReply, error)
	// 修改商铺
	ModifyShopInfo(context.Context, *ModifyShopInfoRequest) (*ModifyShopReply, error)
	// 校验该用户是否是该商铺的核销员
	CheckMobileAccess(context.Context, *CheckMobileAccessRequest) (*CheckMobileAccessReply, error)
}

func RegisterShopControllerServer(s *grpc.Server, srv ShopControllerServer) {
	s.RegisterService(&_ShopController_serviceDesc, srv)
}

func _ShopController_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopControllerServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.ShopController/CreateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopControllerServer).CreateShop(ctx, req.(*CreateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopController_GetShopList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopControllerServer).GetShopList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.ShopController/GetShopList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopControllerServer).GetShopList(ctx, req.(*GetShopListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopController_GetShopInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopControllerServer).GetShopInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.ShopController/GetShopInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopControllerServer).GetShopInfo(ctx, req.(*GetShopInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopController_ModifyShopInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyShopInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopControllerServer).ModifyShopInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.ShopController/ModifyShopInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopControllerServer).ModifyShopInfo(ctx, req.(*ModifyShopInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopController_CheckMobileAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMobileAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopControllerServer).CheckMobileAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.ShopController/CheckMobileAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopControllerServer).CheckMobileAccess(ctx, req.(*CheckMobileAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.pkg.rpc.protos.ShopController",
	HandlerType: (*ShopControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShop",
			Handler:    _ShopController_CreateShop_Handler,
		},
		{
			MethodName: "GetShopList",
			Handler:    _ShopController_GetShopList_Handler,
		},
		{
			MethodName: "GetShopInfo",
			Handler:    _ShopController_GetShopInfo_Handler,
		},
		{
			MethodName: "ModifyShopInfo",
			Handler:    _ShopController_ModifyShopInfo_Handler,
		},
		{
			MethodName: "CheckMobileAccess",
			Handler:    _ShopController_CheckMobileAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}

func init() { proto.RegisterFile("shop.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x8d, 0xed, 0x34, 0x75, 0x6e, 0x9e, 0xda, 0x74, 0xde, 0x6b, 0x9f, 0x15, 0xa1, 0x2a, 0x98,
	0x8d, 0x29, 0x28, 0x40, 0x58, 0x77, 0x51, 0x42, 0x05, 0x45, 0x2d, 0x48, 0x0e, 0x42, 0x02, 0x16,
	0xc8, 0xb1, 0x27, 0x8d, 0xa9, 0xe3, 0x31, 0x33, 0x63, 0xa4, 0xb0, 0xe5, 0x07, 0xd8, 0xf2, 0x19,
	0x7c, 0x01, 0x5f, 0xc2, 0x5f, 0xf0, 0x01, 0xc8, 0x63, 0xc7, 0x76, 0x9c, 0xb8, 0x71, 0x0b, 0x2b,
	0x56, 0xf1, 0x3d, 0x73, 0x67, 0xe6, 0x9e, 0x73, 0xe7, 0x9e, 0x00, 0xb0, 0x09, 0x09, 0x7a, 0x01,
	0x25, 0x9c, 0xa0, 0xff, 0xa7, 0x98, 0xda, 0x13, 0xcb, 0xe7, 0xbd, 0xe0, 0xe2, 0xbc, 0x47, 0x03,
	0x3b, 0xc6, 0x59, 0x67, 0x77, 0xbe, 0xf0, 0xce, 0x26, 0xd3, 0x29, 0xf1, 0x63, 0x5c, 0xff, 0xae,
	0x80, 0x3a, 0x9c, 0x90, 0xe0, 0xc4, 0x1f, 0x13, 0xb4, 0x07, 0x8d, 0xe8, 0xa8, 0x13, 0x47, 0x93,
	0xba, 0x92, 0x51, 0x37, 0x93, 0x08, 0x21, 0xa8, 0xfb, 0xd6, 0x14, 0x6b, 0x72, 0x57, 0x32, 0x9a,
	0xa6, 0xf8, 0x46, 0x3d, 0x40, 0xa3, 0x90, 0xb9, 0x3e, 0x66, 0xec, 0x29, 0x09, 0x29, 0x1b, 0x72,
	0x8b, 0x72, 0x4d, 0xe9, 0x4a, 0x86, 0x62, 0xae, 0x58, 0x41, 0x07, 0xd0, 0x5e, 0x40, 0x8f, 0x7d,
	0x47, 0xab, 0x8b, 0xec, 0x25, 0x1c, 0x0d, 0x62, 0x4a, 0x43, 0x6e, 0xf1, 0x90, 0x69, 0x1b, 0x5d,
	0xc9, 0xd8, 0xea, 0xdf, 0xea, 0x95, 0x30, 0xeb, 0x0d, 0xd3, 0x54, 0x33, 0xb7, 0x0d, 0x75, 0x40,
	0x8d, 0xa2, 0x97, 0xb3, 0x00, 0x6b, 0x0d, 0x71, 0x51, 0x1a, 0xa3, 0x7d, 0x80, 0xf9, 0x69, 0x27,
	0x8e, 0xb6, 0x29, 0xc8, 0xe6, 0x10, 0x74, 0x03, 0x9a, 0x36, 0xc5, 0x16, 0xc7, 0xce, 0x11, 0xd7,
	0x54, 0xc1, 0x3a, 0x03, 0xa2, 0xd5, 0x30, 0x70, 0x92, 0xd5, 0x66, 0xbc, 0x9a, 0x02, 0xc8, 0x80,
	0xed, 0x8f, 0x98, 0xba, 0x63, 0x17, 0xd3, 0x33, 0x32, 0x72, 0x3d, 0xcc, 0x34, 0xe8, 0x2a, 0x46,
	0xd3, 0x2c, 0xc2, 0x51, 0xe6, 0x38, 0x7c, 0x4d, 0xc2, 0xb3, 0xac, 0x94, 0x96, 0x38, 0xad, 0x08,
	0x47, 0x5c, 0x5c, 0x66, 0xe2, 0x91, 0xc5, 0xb1, 0xf6, 0x4f, 0x57, 0x32, 0x54, 0x33, 0x8d, 0xf5,
	0x9f, 0x32, 0xec, 0x0c, 0x44, 0x6d, 0x91, 0x10, 0x26, 0xfe, 0x10, 0x62, 0xc6, 0x0b, 0x0c, 0xa5,
	0x25, 0x86, 0x7f, 0x5d, 0x4b, 0x57, 0xc8, 0xbe, 0x59, 0x59, 0x76, 0x75, 0xbd, 0xec, 0xcd, 0x82,
	0xec, 0x6f, 0x61, 0x3b, 0xaf, 0x7a, 0xe0, 0xcd, 0xd0, 0x7d, 0x50, 0x30, 0xa5, 0x42, 0xec, 0x56,
	0x7f, 0xbf, 0x94, 0xdc, 0x31, 0xa5, 0x84, 0x9a, 0x51, 0x6a, 0x6e, 0xe0, 0xe4, 0xfc, 0xc0, 0xe9,
	0x3f, 0x24, 0x40, 0x4f, 0x30, 0x8f, 0x8e, 0x3e, 0x75, 0x19, 0xaf, 0xda, 0xd4, 0x45, 0x91, 0xe5,
	0xeb, 0x89, 0x9c, 0xd5, 0xa4, 0x14, 0x4d, 0x20, 0xb0, 0xce, 0xb1, 0xe8, 0x70, 0xdd, 0x14, 0xdf,
	0x91, 0x40, 0xd1, 0xef, 0xd0, 0xfd, 0x84, 0x45, 0x4f, 0xeb, 0x66, 0x1a, 0xcf, 0x9b, 0xf5, 0x3c,
	0x7a, 0x65, 0x0d, 0xa1, 0x6f, 0x1a, 0xeb, 0x5f, 0x25, 0x68, 0x2f, 0xf0, 0xbb, 0x9e, 0x7c, 0x87,
	0xb1, 0x77, 0x45, 0x47, 0x68, 0x72, 0x57, 0x31, 0x5a, 0xfd, 0x9b, 0x97, 0xb2, 0x8d, 0x4c, 0xce,
	0x4c, 0xb7, 0xa0, 0xff, 0x60, 0xc3, 0x26, 0xa1, 0xcf, 0x13, 0xa2, 0x71, 0xa0, 0xdf, 0x4d, 0xa5,
	0x17, 0xe9, 0x89, 0xf4, 0x25, 0xd6, 0xa8, 0x7f, 0xce, 0x98, 0xc4, 0xe9, 0x11, 0x93, 0xc3, 0xcc,
	0x53, 0x13, 0x3a, 0x55, 0xeb, 0x12, 0x36, 0x9c, 0x08, 0x21, 0x57, 0x16, 0x42, 0xff, 0xa2, 0xc0,
	0xee, 0x19, 0x71, 0xdc, 0xf1, 0xac, 0x58, 0xf7, 0x7c, 0xce, 0xa5, 0xb5, 0x73, 0x2e, 0x5f, 0x69,
	0xce, 0x95, 0x4a, 0x73, 0x5e, 0xff, 0xfd, 0x39, 0xdf, 0x28, 0xcc, 0x79, 0xd6, 0x88, 0xc6, 0xc2,
	0xf3, 0x5c, 0x67, 0xe9, 0x2b, 0xfc, 0x41, 0xad, 0xec, 0x0f, 0xcd, 0xf5, 0xfe, 0x00, 0xcb, 0xfe,
	0x90, 0x75, 0xe4, 0x4f, 0xfb, 0xc3, 0x33, 0xd0, 0x06, 0x13, 0x6c, 0x5f, 0xc4, 0x25, 0x1f, 0xd9,
	0x36, 0x66, 0x2c, 0xf7, 0x52, 0xa7, 0x02, 0x4e, 0x7a, 0x9e, 0x44, 0xa5, 0x67, 0xbd, 0x87, 0xbd,
	0x15, 0x67, 0x5d, 0xaf, 0xde, 0x7d, 0x00, 0x97, 0xbd, 0x4a, 0xf4, 0x14, 0xf7, 0xa8, 0x66, 0x0e,
	0x39, 0x38, 0x05, 0xc8, 0x5a, 0x8e, 0x76, 0x61, 0x27, 0x8b, 0x1e, 0xe3, 0xb1, 0x15, 0x7a, 0xbc,
	0x5d, 0x43, 0x08, 0xb6, 0x32, 0xf8, 0x45, 0x80, 0xfd, 0xb6, 0x84, 0xfe, 0x85, 0xed, 0x0c, 0x1b,
	0x78, 0x84, 0xe1, 0xb6, 0xdc, 0xff, 0x56, 0x8f, 0x33, 0x07, 0xc4, 0xe7, 0x94, 0x78, 0x1e, 0xa6,
	0xc8, 0x01, 0xc8, 0x5c, 0x19, 0x1d, 0x94, 0xd6, 0xbc, 0xf4, 0x87, 0xd9, 0x31, 0x2a, 0xe5, 0x06,
	0xde, 0x4c, 0xaf, 0xa1, 0x73, 0x68, 0xe5, 0xdc, 0x0b, 0xdd, 0x29, 0xdd, 0xba, 0xec, 0xe1, 0x9d,
	0xdb, 0xd5, 0x92, 0x8b, 0x17, 0x09, 0x63, 0x58, 0x7b, 0x51, 0x6e, 0xf2, 0xd7, 0x5f, 0x94, 0xfa,
	0x95, 0x5e, 0x43, 0x1e, 0x6c, 0x2d, 0xfa, 0x07, 0xea, 0x95, 0x6e, 0x5f, 0x69, 0x34, 0x97, 0xe8,
	0x57, 0x18, 0x03, 0xbd, 0x86, 0x66, 0xb0, 0xb3, 0xf4, 0xe4, 0xd0, 0x83, 0xf2, 0x06, 0x94, 0x3c,
	0xf5, 0xce, 0xbd, 0xab, 0x6c, 0x11, 0x57, 0x3f, 0x52, 0xdf, 0x34, 0xe2, 0x94, 0x51, 0xfc, 0xfb,
	0xf0, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0xd5, 0x6b, 0x84, 0x3e, 0x0b, 0x00, 0x00,
}
