// Code generated by protoc-gen-go. DO NOT EDIT.
// source: staff.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StaffStatus int32

const (
	StaffStatus_StaffStatusDefault StaffStatus = 0
	StaffStatus_StaffStatusOpen    StaffStatus = 1
	StaffStatus_StaffStatusClose   StaffStatus = 2
)

var StaffStatus_name = map[int32]string{
	0: "StaffStatusDefault",
	1: "StaffStatusOpen",
	2: "StaffStatusClose",
}
var StaffStatus_value = map[string]int32{
	"StaffStatusDefault": 0,
	"StaffStatusOpen":    1,
	"StaffStatusClose":   2,
}

func (x StaffStatus) String() string {
	return proto.EnumName(StaffStatus_name, int32(x))
}
func (StaffStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type StaffInfo struct {
	StaffId   uint64      `protobuf:"varint,1,opt,name=staffId" json:"staffId,omitempty"`
	ShopId    uint64      `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
	Name      string      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mobile    string      `protobuf:"bytes,4,opt,name=mobile" json:"mobile,omitempty"`
	CreatedAt string      `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt string      `protobuf:"bytes,6,opt,name=updatedAt" json:"updatedAt,omitempty"`
	IsRebate  bool        `protobuf:"varint,7,opt,name=isRebate" json:"isRebate,omitempty"`
	Status    StaffStatus `protobuf:"varint,8,opt,name=status,enum=merchant.pkg.rpc.protos.StaffStatus" json:"status,omitempty"`
}

func (m *StaffInfo) Reset()                    { *m = StaffInfo{} }
func (m *StaffInfo) String() string            { return proto.CompactTextString(m) }
func (*StaffInfo) ProtoMessage()               {}
func (*StaffInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *StaffInfo) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

func (m *StaffInfo) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *StaffInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StaffInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *StaffInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *StaffInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *StaffInfo) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

func (m *StaffInfo) GetStatus() StaffStatus {
	if m != nil {
		return m.Status
	}
	return StaffStatus_StaffStatusDefault
}

type CreateStaffInfoRequest struct {
	ShopId   uint64      `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Name     string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mobile   string      `protobuf:"bytes,3,opt,name=mobile" json:"mobile,omitempty"`
	IsRebate bool        `protobuf:"varint,4,opt,name=isRebate" json:"isRebate,omitempty"`
	Status   StaffStatus `protobuf:"varint,5,opt,name=status,enum=merchant.pkg.rpc.protos.StaffStatus" json:"status,omitempty"`
}

func (m *CreateStaffInfoRequest) Reset()                    { *m = CreateStaffInfoRequest{} }
func (m *CreateStaffInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffInfoRequest) ProtoMessage()               {}
func (*CreateStaffInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CreateStaffInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CreateStaffInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStaffInfoRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CreateStaffInfoRequest) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

func (m *CreateStaffInfoRequest) GetStatus() StaffStatus {
	if m != nil {
		return m.Status
	}
	return StaffStatus_StaffStatusDefault
}

type CreateStaffInfoReply struct {
	Err       *Error     `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	StaffInfo *StaffInfo `protobuf:"bytes,2,opt,name=staffInfo" json:"staffInfo,omitempty"`
}

func (m *CreateStaffInfoReply) Reset()                    { *m = CreateStaffInfoReply{} }
func (m *CreateStaffInfoReply) String() string            { return proto.CompactTextString(m) }
func (*CreateStaffInfoReply) ProtoMessage()               {}
func (*CreateStaffInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *CreateStaffInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreateStaffInfoReply) GetStaffInfo() *StaffInfo {
	if m != nil {
		return m.StaffInfo
	}
	return nil
}

type GetStaffListRequest struct {
	ShopId   uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Page     uint64 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize uint64 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	UserName string `protobuf:"bytes,4,opt,name=userName" json:"userName,omitempty"`
}

func (m *GetStaffListRequest) Reset()                    { *m = GetStaffListRequest{} }
func (m *GetStaffListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStaffListRequest) ProtoMessage()               {}
func (*GetStaffListRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GetStaffListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetStaffListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetStaffListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetStaffListRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type GetStaffListReply struct {
	Err       *Error       `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	StaffList []*StaffInfo `protobuf:"bytes,2,rep,name=StaffList" json:"StaffList,omitempty"`
	Count     uint64       `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetStaffListReply) Reset()                    { *m = GetStaffListReply{} }
func (m *GetStaffListReply) String() string            { return proto.CompactTextString(m) }
func (*GetStaffListReply) ProtoMessage()               {}
func (*GetStaffListReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *GetStaffListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetStaffListReply) GetStaffList() []*StaffInfo {
	if m != nil {
		return m.StaffList
	}
	return nil
}

func (m *GetStaffListReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetStaffInfoRequest struct {
	StaffId uint64 `protobuf:"varint,1,opt,name=staffId" json:"staffId,omitempty"`
}

func (m *GetStaffInfoRequest) Reset()                    { *m = GetStaffInfoRequest{} }
func (m *GetStaffInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStaffInfoRequest) ProtoMessage()               {}
func (*GetStaffInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *GetStaffInfoRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

type GetStaffInfoReply struct {
	Err       *Error     `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	StaffInfo *StaffInfo `protobuf:"bytes,2,opt,name=StaffInfo" json:"StaffInfo,omitempty"`
}

func (m *GetStaffInfoReply) Reset()                    { *m = GetStaffInfoReply{} }
func (m *GetStaffInfoReply) String() string            { return proto.CompactTextString(m) }
func (*GetStaffInfoReply) ProtoMessage()               {}
func (*GetStaffInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *GetStaffInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetStaffInfoReply) GetStaffInfo() *StaffInfo {
	if m != nil {
		return m.StaffInfo
	}
	return nil
}

type ModifyStaffInfoRequest struct {
	Name     string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Mobile   string      `protobuf:"bytes,2,opt,name=mobile" json:"mobile,omitempty"`
	ShopId   uint64      `protobuf:"varint,3,opt,name=shopId" json:"shopId,omitempty"`
	StaffId  uint64      `protobuf:"varint,4,opt,name=staffId" json:"staffId,omitempty"`
	IsRebate bool        `protobuf:"varint,5,opt,name=isRebate" json:"isRebate,omitempty"`
	Status   StaffStatus `protobuf:"varint,6,opt,name=status,enum=merchant.pkg.rpc.protos.StaffStatus" json:"status,omitempty"`
}

func (m *ModifyStaffInfoRequest) Reset()                    { *m = ModifyStaffInfoRequest{} }
func (m *ModifyStaffInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyStaffInfoRequest) ProtoMessage()               {}
func (*ModifyStaffInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *ModifyStaffInfoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyStaffInfoRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ModifyStaffInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ModifyStaffInfoRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

func (m *ModifyStaffInfoRequest) GetIsRebate() bool {
	if m != nil {
		return m.IsRebate
	}
	return false
}

func (m *ModifyStaffInfoRequest) GetStatus() StaffStatus {
	if m != nil {
		return m.Status
	}
	return StaffStatus_StaffStatusDefault
}

type ModifyStaffInfoReply struct {
	Err       *Error     `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	StaffInfo *StaffInfo `protobuf:"bytes,2,opt,name=staffInfo" json:"staffInfo,omitempty"`
}

func (m *ModifyStaffInfoReply) Reset()                    { *m = ModifyStaffInfoReply{} }
func (m *ModifyStaffInfoReply) String() string            { return proto.CompactTextString(m) }
func (*ModifyStaffInfoReply) ProtoMessage()               {}
func (*ModifyStaffInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *ModifyStaffInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ModifyStaffInfoReply) GetStaffInfo() *StaffInfo {
	if m != nil {
		return m.StaffInfo
	}
	return nil
}

type RemoveStaffRequest struct {
	StaffId uint64 `protobuf:"varint,1,opt,name=staffId" json:"staffId,omitempty"`
}

func (m *RemoveStaffRequest) Reset()                    { *m = RemoveStaffRequest{} }
func (m *RemoveStaffRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveStaffRequest) ProtoMessage()               {}
func (*RemoveStaffRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *RemoveStaffRequest) GetStaffId() uint64 {
	if m != nil {
		return m.StaffId
	}
	return 0
}

type RemoveStaffReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *RemoveStaffReply) Reset()                    { *m = RemoveStaffReply{} }
func (m *RemoveStaffReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveStaffReply) ProtoMessage()               {}
func (*RemoveStaffReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *RemoveStaffReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *RemoveStaffReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*StaffInfo)(nil), "merchant.pkg.rpc.protos.StaffInfo")
	proto.RegisterType((*CreateStaffInfoRequest)(nil), "merchant.pkg.rpc.protos.CreateStaffInfoRequest")
	proto.RegisterType((*CreateStaffInfoReply)(nil), "merchant.pkg.rpc.protos.CreateStaffInfoReply")
	proto.RegisterType((*GetStaffListRequest)(nil), "merchant.pkg.rpc.protos.GetStaffListRequest")
	proto.RegisterType((*GetStaffListReply)(nil), "merchant.pkg.rpc.protos.GetStaffListReply")
	proto.RegisterType((*GetStaffInfoRequest)(nil), "merchant.pkg.rpc.protos.GetStaffInfoRequest")
	proto.RegisterType((*GetStaffInfoReply)(nil), "merchant.pkg.rpc.protos.GetStaffInfoReply")
	proto.RegisterType((*ModifyStaffInfoRequest)(nil), "merchant.pkg.rpc.protos.ModifyStaffInfoRequest")
	proto.RegisterType((*ModifyStaffInfoReply)(nil), "merchant.pkg.rpc.protos.ModifyStaffInfoReply")
	proto.RegisterType((*RemoveStaffRequest)(nil), "merchant.pkg.rpc.protos.RemoveStaffRequest")
	proto.RegisterType((*RemoveStaffReply)(nil), "merchant.pkg.rpc.protos.RemoveStaffReply")
	proto.RegisterEnum("merchant.pkg.rpc.protos.StaffStatus", StaffStatus_name, StaffStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StaffController service

type StaffControllerClient interface {
	// 获取员工信息
	Get(ctx context.Context, in *GetStaffInfoRequest, opts ...grpc.CallOption) (*GetStaffInfoReply, error)
	// 获取员工列表
	GetList(ctx context.Context, in *GetStaffListRequest, opts ...grpc.CallOption) (*GetStaffListReply, error)
	// 创建
	Create(ctx context.Context, in *CreateStaffInfoRequest, opts ...grpc.CallOption) (*CreateStaffInfoReply, error)
	// 修改
	Modify(ctx context.Context, in *ModifyStaffInfoRequest, opts ...grpc.CallOption) (*ModifyStaffInfoReply, error)
	// 删除
	Remove(ctx context.Context, in *RemoveStaffRequest, opts ...grpc.CallOption) (*RemoveStaffReply, error)
}

type staffControllerClient struct {
	cc *grpc.ClientConn
}

func NewStaffControllerClient(cc *grpc.ClientConn) StaffControllerClient {
	return &staffControllerClient{cc}
}

func (c *staffControllerClient) Get(ctx context.Context, in *GetStaffInfoRequest, opts ...grpc.CallOption) (*GetStaffInfoReply, error) {
	out := new(GetStaffInfoReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.StaffController/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffControllerClient) GetList(ctx context.Context, in *GetStaffListRequest, opts ...grpc.CallOption) (*GetStaffListReply, error) {
	out := new(GetStaffListReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.StaffController/GetList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffControllerClient) Create(ctx context.Context, in *CreateStaffInfoRequest, opts ...grpc.CallOption) (*CreateStaffInfoReply, error) {
	out := new(CreateStaffInfoReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.StaffController/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffControllerClient) Modify(ctx context.Context, in *ModifyStaffInfoRequest, opts ...grpc.CallOption) (*ModifyStaffInfoReply, error) {
	out := new(ModifyStaffInfoReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.StaffController/Modify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffControllerClient) Remove(ctx context.Context, in *RemoveStaffRequest, opts ...grpc.CallOption) (*RemoveStaffReply, error) {
	out := new(RemoveStaffReply)
	err := grpc.Invoke(ctx, "/merchant.pkg.rpc.protos.StaffController/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StaffController service

type StaffControllerServer interface {
	// 获取员工信息
	Get(context.Context, *GetStaffInfoRequest) (*GetStaffInfoReply, error)
	// 获取员工列表
	GetList(context.Context, *GetStaffListRequest) (*GetStaffListReply, error)
	// 创建
	Create(context.Context, *CreateStaffInfoRequest) (*CreateStaffInfoReply, error)
	// 修改
	Modify(context.Context, *ModifyStaffInfoRequest) (*ModifyStaffInfoReply, error)
	// 删除
	Remove(context.Context, *RemoveStaffRequest) (*RemoveStaffReply, error)
}

func RegisterStaffControllerServer(s *grpc.Server, srv StaffControllerServer) {
	s.RegisterService(&_StaffController_serviceDesc, srv)
}

func _StaffController_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffControllerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.StaffController/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffControllerServer).Get(ctx, req.(*GetStaffInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffController_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffControllerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.StaffController/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffControllerServer).GetList(ctx, req.(*GetStaffListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffController_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStaffInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffControllerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.StaffController/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffControllerServer).Create(ctx, req.(*CreateStaffInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffController_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyStaffInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffControllerServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.StaffController/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffControllerServer).Modify(ctx, req.(*ModifyStaffInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffController_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffControllerServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.pkg.rpc.protos.StaffController/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffControllerServer).Remove(ctx, req.(*RemoveStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StaffController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.pkg.rpc.protos.StaffController",
	HandlerType: (*StaffControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StaffController_Get_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _StaffController_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StaffController_Create_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _StaffController_Modify_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _StaffController_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staff.proto",
}

func init() { proto.RegisterFile("staff.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcf, 0xae, 0xd2, 0x4e,
	0x14, 0x66, 0x68, 0xe9, 0x85, 0x43, 0xf2, 0xfb, 0xe1, 0x5c, 0xc4, 0x86, 0x18, 0x43, 0x1a, 0x17,
	0x78, 0xd5, 0x5e, 0x83, 0x5b, 0x17, 0x2a, 0x1a, 0x42, 0xe2, 0xbf, 0x94, 0x9d, 0x31, 0x31, 0x05,
	0x86, 0x7b, 0xd1, 0xb6, 0x53, 0x67, 0xa6, 0x26, 0xf8, 0x02, 0x26, 0xbe, 0x80, 0x2b, 0x5f, 0xc3,
	0xe7, 0xf0, 0x8d, 0x34, 0x9d, 0x29, 0xa5, 0x0d, 0x2d, 0xb7, 0xc1, 0x85, 0x2b, 0xe6, 0xfc, 0x9b,
	0xf3, 0x9d, 0xaf, 0xe7, 0x1b, 0xa0, 0xcd, 0x85, 0xbb, 0x5a, 0xd9, 0x21, 0xa3, 0x82, 0xe2, 0x1b,
	0x3e, 0x61, 0x8b, 0x4b, 0x37, 0x10, 0x76, 0xf8, 0xf1, 0xc2, 0x66, 0xe1, 0x42, 0xf9, 0x79, 0xff,
	0xfa, 0x36, 0xf0, 0x7e, 0x41, 0x7d, 0x9f, 0x06, 0xca, 0x6f, 0xfd, 0x46, 0xd0, 0x9a, 0xc5, 0xf5,
	0xd3, 0x60, 0x45, 0xb1, 0x09, 0x27, 0xf2, 0xb2, 0xe9, 0xd2, 0x44, 0x03, 0x34, 0xd4, 0x9d, 0xad,
	0x89, 0x7b, 0x60, 0xf0, 0x4b, 0x1a, 0x4e, 0x97, 0x66, 0x5d, 0x06, 0x12, 0x0b, 0x63, 0xd0, 0x03,
	0xd7, 0x27, 0xa6, 0x36, 0x40, 0xc3, 0x96, 0x23, 0xcf, 0x71, 0xae, 0x4f, 0xe7, 0x6b, 0x8f, 0x98,
	0xba, 0xf4, 0x26, 0x16, 0xbe, 0x09, 0xad, 0x05, 0x23, 0xae, 0x20, 0xcb, 0x27, 0xc2, 0x6c, 0xc8,
	0xd0, 0xce, 0x11, 0x47, 0xa3, 0x70, 0x99, 0x44, 0x0d, 0x15, 0x4d, 0x1d, 0xb8, 0x0f, 0xcd, 0x35,
	0x77, 0xc8, 0xdc, 0x15, 0xc4, 0x3c, 0x19, 0xa0, 0x61, 0xd3, 0x49, 0x6d, 0xfc, 0x08, 0x0c, 0x2e,
	0x5c, 0x11, 0x71, 0xb3, 0x39, 0x40, 0xc3, 0xff, 0x46, 0xb7, 0xed, 0x12, 0x12, 0x6c, 0x39, 0xe9,
	0x4c, 0xe6, 0x3a, 0x49, 0x8d, 0xf5, 0x13, 0x41, 0x6f, 0x2c, 0x51, 0xa4, 0x3c, 0x38, 0xe4, 0x53,
	0x44, 0xb8, 0xc8, 0x0c, 0x8d, 0x0a, 0x87, 0xae, 0x17, 0x0e, 0xad, 0xe5, 0x86, 0xce, 0x02, 0xd7,
	0x4b, 0x81, 0x37, 0x8e, 0x00, 0xfe, 0x0d, 0x41, 0x77, 0x0f, 0x78, 0xe8, 0x6d, 0xf0, 0x03, 0xd0,
	0x08, 0x63, 0x12, 0x73, 0x7b, 0x74, 0xab, 0xf4, 0xce, 0xe7, 0x8c, 0x51, 0xe6, 0xc4, 0xa9, 0xf8,
	0x31, 0xb4, 0xf8, 0xf6, 0x0e, 0x39, 0x55, 0x7b, 0x64, 0x1d, 0xc6, 0x22, 0xbb, 0xed, 0x8a, 0xac,
	0x0d, 0x9c, 0x4e, 0x88, 0x90, 0xa1, 0x17, 0x6b, 0x2e, 0x2a, 0x30, 0x18, 0xba, 0x17, 0x24, 0x59,
	0x26, 0x79, 0x8e, 0x99, 0x8a, 0x7f, 0x67, 0xeb, 0x2f, 0x8a, 0x43, 0xdd, 0x49, 0xed, 0x38, 0x16,
	0x71, 0xc2, 0x5e, 0xc5, 0xac, 0xab, 0xa5, 0x4a, 0x6d, 0xeb, 0x07, 0x82, 0x6b, 0xf9, 0xde, 0x47,
	0x93, 0x90, 0xde, 0x61, 0xd6, 0x07, 0x5a, 0x55, 0x12, 0xd2, 0x22, 0xdc, 0x85, 0xc6, 0x82, 0x46,
	0x81, 0x48, 0xe0, 0x2b, 0xc3, 0x3a, 0xdf, 0x51, 0x93, 0x5d, 0xae, 0x52, 0xad, 0x59, 0x5f, 0x33,
	0x03, 0xfd, 0xe5, 0x57, 0x9d, 0x1d, 0xf3, 0x55, 0xd3, 0xa3, 0xf5, 0x0b, 0x41, 0xef, 0x25, 0x5d,
	0xae, 0x57, 0x9b, 0x3d, 0xf8, 0x5b, 0x0d, 0xa0, 0x42, 0x0d, 0xd4, 0x73, 0x1a, 0xd8, 0x6d, 0x81,
	0x96, 0xdb, 0x82, 0x0c, 0x05, 0x7a, 0xfe, 0xb9, 0xc9, 0xaa, 0xa6, 0x51, 0xaa, 0x1a, 0xe3, 0x48,
	0xd5, 0xec, 0x8d, 0xf4, 0xaf, 0x54, 0x63, 0x03, 0x76, 0x88, 0x4f, 0x3f, 0x2b, 0x05, 0x5f, 0xbd,
	0x19, 0xef, 0xa0, 0x93, 0xcb, 0x3f, 0x0e, 0x77, 0x0f, 0x0c, 0x46, 0x78, 0xe4, 0x09, 0x09, 0xba,
	0xe9, 0x24, 0xd6, 0xd9, 0x1b, 0x68, 0x67, 0x18, 0xc3, 0x3d, 0xc0, 0x19, 0xf3, 0x19, 0x59, 0xb9,
	0x91, 0x27, 0x3a, 0x35, 0x7c, 0x0a, 0xff, 0x67, 0xfc, 0xaf, 0x43, 0x12, 0x74, 0x10, 0xee, 0x42,
	0x27, 0xe3, 0x1c, 0x7b, 0x94, 0x93, 0x4e, 0x7d, 0xf4, 0x5d, 0x4f, 0x72, 0xc7, 0x34, 0x10, 0x8c,
	0x7a, 0x1e, 0x61, 0xd8, 0x05, 0x6d, 0x42, 0x04, 0xbe, 0x57, 0x8a, 0xb4, 0x40, 0x2c, 0xfd, 0xb3,
	0x8a, 0xd9, 0xa1, 0xb7, 0xb1, 0x6a, 0x98, 0xc0, 0xc9, 0x84, 0x08, 0x29, 0xc9, 0xab, 0xdb, 0x64,
	0x9e, 0xab, 0x0a, 0x6d, 0xd2, 0x07, 0xc6, 0xaa, 0xe1, 0x0f, 0x60, 0xa8, 0xf7, 0x17, 0x9f, 0x97,
	0xd6, 0x15, 0xff, 0xb3, 0xf4, 0xef, 0x57, 0x2f, 0x48, 0x7b, 0xa9, 0xad, 0x3d, 0xd0, 0xab, 0x58,
	0xa9, 0x07, 0x7a, 0x15, 0xe9, 0xc0, 0xaa, 0xe1, 0x39, 0x18, 0x6a, 0xcb, 0xf0, 0xdd, 0xd2, 0xd2,
	0xfd, 0xb5, 0xed, 0xdf, 0xa9, 0x96, 0x2c, 0x7b, 0x3c, 0x6d, 0xbe, 0x35, 0x54, 0x70, 0xae, 0x7e,
	0x1f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x85, 0x0a, 0x84, 0xc7, 0x08, 0x00, 0x00,
}
